In [1]:
import pandas as pd

data=pd.read_excel(r"C:\Users\MRITH\Downloads\Mock_Project\PropertySummary.xlsx")
data.head()

Property_id                                           Name  \
0     29846605          Two stylish joint studios in Neukölln   
1     29813399                 Living in young Friedrichshain   
2     29794793  Schöne ruhige Unterkunft im Herzen von Berlin   
3     29750208                Simondach - the heart of Berlin   
4     29727312                Luminous penthouse design suite   

  Experiences_offered  thumbnail_url  medium_url  xl_picture_url  \
0                none            NaN         NaN             NaN   
1                none            NaN         NaN             NaN   
2                none            NaN         NaN             NaN   
3                none            NaN         NaN             NaN   
4                none            NaN         NaN             NaN   

   Attendent_id Attendent_name  Attendent_since       Attendent_location  ...  \
0       5129957           Alex          41323.0  Berlin, Berlin, Germany  ...   
1      64166708  María Del Mar          42452.0  Berlin, Berlin, Germany  ...   
2     224156706            Cem          43408.0  Berlin, Berlin, Germany  ...   
3      21445063   Joana Karina          41899.0  Berlin, Berlin, Germany  ...   
4     135973285          Naomi          42906.0  Berlin, Berlin, Germany  ...   

  review_scores_location  review_scores_value  requires_license  \
0                    NaN                  NaN                 t   
1                    NaN                  NaN                 t   
2                    NaN                  NaN                 t   
3                    NaN                  NaN                 t   
4                    NaN                  NaN                 t   

                                  license instant_bookable  \
0                       08/Z/RA/006663-18                f   
1  02/Z/ZA/004738-17 Mindestaufenthalt 60                t   
2                       02/Z/AZ/008691-18                t   
3                       02/Z/AZ/009014-18                f   
4                            HR B 166587B                f   

   is_business_travel_ready          cancellation_policy  \
0                         f                     flexible   
1                         f  strict_14_with_grace_period   
2                         f                     flexible   
3                         f                     flexible   
4                         f                     moderate   

  require_guest_profile_picture require_guest_phone_verification  \
0                             f                                f   
1                             f                                f   
2                             f                                f   
3                             f                                f   
4                             f                                f   

  reviews_per_month  
0               NaN  
1               NaN  
2               NaN  
3               NaN  
4               NaN  

[5 rows x 71 columns]

In [5]:
data.dtypes

Property_id                           int64
Name                                 object
Experiences_offered                  object
thumbnail_url                       float64
medium_url                          float64
xl_picture_url                      float64
Attendent_id                          int64
Attendent_name                       object
Attendent_since                     float64
Attendent_location                   object
Attendent_response_time              object
Attendent_response_rate             float64
Attendent_acceptance_rate           float64
Attendent_is_superAttendent          object
Attendent_neighbourhood              object
Attendent_Propertys_count           float64
Attendent_total_Propertys_count     float64
Attendent_verifications              object
Attendent_has_profile_pic            object
Attendent_identity_verified          object
neighbourhood                        object
neighbourhood_cleansed               object
neighbourhood_group_cleansed    

In [4]:
pd.set_option('display.max_rows', None)

pd.set_option('display.max_columns', None)

In [3]:
data.columns = [col.lower().replace(' ', '_') for col in data.columns]

In [10]:
data['availability_30'].describe()

count    22552.000000
mean         4.944173
std          8.677395
min          0.000000
25%          0.000000
50%          0.000000
75%          6.000000
max         30.000000
Name: availability_30, dtype: float64

ZipCode

In [29]:
data['zipcode'].unique()

array([12045., 10247., 10963., 10245., 10115., 10243., 10779., 12681.,
       10719., 12105., 10179., 13359., 12043., 10435., 10437., 13347.,
       13158., 10119., 10999., 13509., 12051., 10627., 10318., 10559.,
       12049., 10555., 10557., 13357., 10827., 10777., 10407., 14059.,
       10965., 14197., 10961., 10789., 13156., 10717., 10585., 10117.,
       12159., 10178., 10249., 12489., 13189., 12683., 12277., 14193.,
       12055., 10997., 10829., 12161., 10317., 13627., 10439., 14195.,
       13055., 10707., 10969., 13581., 12203., 13353., 10967., 12527.,
       10551.,    nan, 13086., 10589., 10781., 10405., 12059., 10625.,
       12587., 12053., 13409., 10787., 10587., 10365., 14089., 12435.,
       12305., 13465., 10823., 13591., 12047., 10319., 13187., 13351.,
       12347., 13407., 12103., 12589., 10409., 12307., 13127., 10783.,
       10629., 13503., 14167., 13587., 13595., 13629., 12623., 14057.,
       10711., 12101., 10825., 10709., 10715., 10623., 13088., 12163.,
      

In [5]:
def clean_zipcode(zipcode):
    if isinstance(zipcode, str):
        cleaned = re.findall(r'\d+', zipcode)
        cleaned_zipcodes = [num for num in cleaned if 4 <= len(num) <= 5] 
        
        if cleaned_zipcodes:
            return int(cleaned_zipcodes[0])
        else:
            return np.nan

    return zipcode  

In [6]:
import re
data['zipcode'] = data['zipcode'].apply(clean_zipcode)

In [21]:
data['zipcode'] = data['zipcode'].fillna(-1).replace([float('inf'), -float('inf')], -1)

data['zipcode'] = data['zipcode'].astype(int)

four_digit_zipcodes = data[data['zipcode'].between(1000, 9999)]

print(four_digit_zipcodes)

       property_id                               name experiences_offered  \
6349       7609649       Cosy room in the place to be                none   
17038     26644976               Sunshine Cute Roommy                none   
17051     26652984                Home Sunshine Lucky                none   
17060     26652896                   Hilarious Banana                none   
17068     26653275                         Cute Cutey                none   
17117     26652138                      Bubble Roommy                none   
17126     26757806  Freedom Extravaganza Cosmopolitan                none   
17128     26652240      Sentiment Small Sophisticated                none   

       thumbnail_url  medium_url  xl_picture_url  attendent_id attendent_name  \
6349             NaN         NaN             NaN      19666549     Noam Enrio   
17038            NaN         NaN             NaN     200309028       Xingying   
17051            NaN         NaN             NaN     200357153 

In [23]:
data.loc[data['property_id'] == 7609649, 'zipcode'] = 10407
data.loc[data['property_id'] == 26644976, 'zipcode'] = 13629
data.loc[data['property_id'] == 26652984, 'zipcode'] = 13595
data.loc[data['property_id'] == 26652896, 'zipcode'] = 13357
data.loc[data['property_id'] == 26653275, 'zipcode'] = 12621
data.loc[data['property_id'] == 26652138, 'zipcode'] = 12629
data.loc[data['property_id'] == 26757806, 'zipcode'] = 10789
data.loc[data['property_id'] == 26652240, 'zipcode'] = 12621

In [46]:
data['zipcode'].fillna(0, inplace=True)
data['zipcode'] = data['zipcode'].astype(int)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_5112\10661685.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['zipcode'].fillna(0, inplace=True)  # Using -1 as a placeholder for missing values


In [26]:
import numpy as np
data['zipcode']=data['zipcode'].replace(-1,np.nan)

'neighboured_group_cleansed'

In [30]:
neighboured_group_cleansed = data['neighbourhood_group_cleansed'].unique()
neighboured_group_cleansed_list = neighboured_group_cleansed.tolist()
print(neighboured_group_cleansed_list)

['Neukölln', 'Friedrichshain-Kreuzberg', 'Mitte', 'Charlottenburg-Wilm.', 'Marzahn - Hellersdorf', 'Tempelhof - Schöneberg', 'Pankow', 'Reinickendorf', 'Lichtenberg', 'Treptow - Köpenick', 'Spandau', 'Steglitz - Zehlendorf']


In [31]:
def clean_neighbourhood(name):
    cleaned_name = name.replace(' - ', '-').strip()
    cleaned_name = cleaned_name.replace('.', '')
    cleaned_name = cleaned_name.strip() 
    return cleaned_name.lower() 

data['neighbourhood_group_cleansed'] = data['neighbourhood_group_cleansed'].apply(clean_neighbourhood)


In [32]:
data['neighbourhood_group_cleansed'].unique()

array(['neukölln', 'friedrichshain-kreuzberg', 'mitte',
       'charlottenburg-wilm', 'marzahn-hellersdorf',
       'tempelhof-schöneberg', 'pankow', 'reinickendorf', 'lichtenberg',
       'treptow-köpenick', 'spandau', 'steglitz-zehlendorf'], dtype=object)

neighbourhood_cleansed

In [33]:
neighboured_cleansed = data['neighbourhood_cleansed'].unique()
neighboured_cleansed_list = neighboured_cleansed.tolist()
print(neighboured_cleansed_list)

['Reuterstraße', 'Frankfurter Allee Nord', 'Tempelhofer Vorstadt', 'Frankfurter Allee Süd FK', 'Brunnenstr. Süd', 'Karl-Marx-Allee-Süd', 'Düsseldorfer Straße', 'Marzahn-Süd', 'Mariendorf', 'Alexanderplatz', 'Osloer Straße', 'Prenzlauer Berg Südwest', 'Prenzlauer Berg Nordwest', 'Brunnenstr. Nord', 'Prenzlauer Berg Ost', 'Blankenfelde/Niederschönhausen', 'Südliche Friedrichstadt', 'Tiergarten Süd', 'West 3', 'Neuköllner Mitte/Zentrum', 'Kantstraße', 'Karlshorst', 'Moabit Ost', 'Moabit West', 'Schöneberg-Nord', 'Schloß Charlottenburg', 'Wiesbadener Straße', 'Schönholz/Wilhelmsruh/Rosenthal', 'Volkspark Wilmersdorf', 'Otto-Suhr-Allee', 'Regierungsviertel', 'Friedenau', 'Schillerpromenade', 'Adlershof', 'Schöneberg-Süd', 'Pankow Süd', 'südliche Luisenstadt', 'Biesdorf', 'Marienfelde', 'Grunewald', 'Rixdorf', 'nördliche Luisenstadt', 'Neu Lichtenberg', 'Charlottenburg Nord', 'Schmargendorf', 'Alt-Hohenschönhausen Süd', 'Prenzlauer Berg Süd', 'Wilhelmstadt', 'Drakestr.', 'Wedding Zentrum', '

In [35]:
def clean_neighbourhood(neighbourhood):
    if isinstance(neighbourhood, str):
        neighbourhood = neighbourhood.replace('.', '')
        neighbourhood = neighbourhood.strip()
        neighbourhood = neighbourhood.lower()
        neighbourhood = neighbourhood.replace(' - ', '-')
    return neighbourhood

data['neighbourhood_cleansed'] = data['neighbourhood_cleansed'].apply(clean_neighbourhood)


neighbourhood

In [38]:
data['neighbourhood'].unique()

array(['Neukölln', 'Friedrichshain', 'Kreuzberg', 'Mitte', 'Wilmersdorf',
       'Marzahn', 'Mariendorf', 'Wedding', 'Prenzlauer Berg', 'Rosenthal',
       'Tiergarten', 'Tegel', 'Charlottenburg', 'Karlshorst', 'Moabit',
       'Schöneberg', 'Niederschönhausen', 'Friedenau', 'Adlershof',
       'Pankow', 'Biesdorf', 'Marienfelde', 'Schmargendorf',
       'Rummelsburg', 'Charlottenburg-Nord', 'Alt-Hohenschönhausen',
       'Grunewald', 'Spandau', 'Lichterfelde', 'Schmöckwitz', 'Weißensee',
       'Friedrichshagen', 'Lichtenberg', 'Kladow', 'Plänterwald',
       'Lichtenrade', 'Frohnau', 'Staaken', 'Friedrichsfelde',
       'Alt-Treptow', 'Britz', 'Reinickendorf', 'Tempelhof', 'Rahnsdorf',
       'Dahlem', 'Hansaviertel', 'NA', 'Französisch Buchholz',
       'Heiligensee', 'Wilhelmstadt', 'Siemensstadt', 'Mahlsdorf',
       'Steglitz', 'Haselhorst', 'Gropiusstadt', 'Nikolassee', 'Westend',
       'Oberschöneweide', 'Halensee', 'Kaulsdorf', 'Johannisthal',
       'Müggelheim', 'Köpenick',

In [37]:
data['neighbourhood'] = (data['neighbourhood'].fillna('NA'))

Attendent_identity_verified

In [39]:
data['attendent_identity_verified'].fillna('NA',inplace=True)
data['attendent_identity_verified'] = data['attendent_identity_verified'].replace({'t': True, 'f': False})

C:\Users\MRITH\AppData\Local\Temp\ipykernel_17348\1599907828.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['attendent_identity_verified'].fillna('NA',inplace=True)


In [40]:
data['attendent_identity_verified'].value_counts()

attendent_identity_verified
False    13824
True      8702
NA          26
Name: count, dtype: int64

Attendent_has_profile_pic

In [41]:
data['attendent_has_profile_pic'].value_counts()

attendent_has_profile_pic
t    22470
f       56
Name: count, dtype: int64

In [42]:
data['attendent_has_profile_pic'] = data['attendent_has_profile_pic'].replace({'t': True, 'f': False})

Attendent_verifications

In [43]:
data['attendent_verifications'] = (
    data['attendent_verifications']
    .str.replace(r'\[|\]', '', regex=True) 
    .str.replace('\'', '') 
    .str.replace(' ','')             
    .str.strip()                            
    .str.lower()                            
)

In [44]:
data['attendent_verifications'].unique()


array(['email,phone,reviews,offline_government_id,selfie,government_id,identity_manual',
       'email,phone', 'email,phone,facebook,reviews,jumio,government_id',
       'email,phone,reviews,jumio,offline_government_id,selfie,government_id,identity_manual',
       'email,phone,google,reviews,jumio,offline_government_id,kba,selfie,government_id,identity_manual',
       'email,phone,facebook,reviews,manual_offline,jumio,selfie,government_id,identity_manual',
       'email,identity_manual',
       'email,phone,jumio,offline_government_id,selfie,government_id,identity_manual',
       '', 'email,phone,reviews,jumio,government_id',
       'email,phone,jumio,offline_government_id,government_id',
       'email,phone,reviews',
       'email,phone,manual_offline,jumio,selfie,government_id,identity_manual',
       'email,phone,reviews,manual_offline,jumio,government_id,work_email',
       'phone,work_email', 'email,phone,facebook,jumio,government_id',
       'email,phone,offline_government_id,gov

In [45]:
data['attendent_verifications'].fillna('NA',inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_17348\1150166926.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['attendent_verifications'].fillna('NA',inplace=True)


In [46]:
data['attendent_verifications'].isnull().sum()

0

attendent_total_propertys_count

In [47]:
data['attendent_total_propertys_count'].fillna(np.nan,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_17348\2005019245.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['attendent_total_propertys_count'].fillna(np.nan,inplace=True)


In [48]:
data['attendent_total_propertys_count'].isnull().sum()

26

attendent_propertys_count

In [49]:
data['attendent_propertys_count'].fillna(np.nan,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_17348\34903139.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['attendent_propertys_count'].fillna(np.nan,inplace=True)


In [50]:
data['attendent_propertys_count'].isnull().sum()

26

attendent_neighbourhood

In [51]:
data['attendent_neighbourhood'] = data['attendent_neighbourhood'].str.replace('.', '', regex=False)
data['attendent_neighbourhood'] = data['attendent_neighbourhood'].str.strip()
data['attendent_neighbourhood'] = data['attendent_neighbourhood'].str.lower() 

In [52]:
data['attendent_neighbourhood'].fillna('NA',inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_17348\2991031102.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['attendent_neighbourhood'].fillna('NA',inplace=True)


attendent_is_superattendent

In [53]:
data['attendent_is_superattendent'].fillna('NA',inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_17348\155418090.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['attendent_is_superattendent'].fillna('NA',inplace=True)


In [54]:
data['attendent_is_superattendent'].replace({'f':False,'t':True},inplace=True)

In [55]:
data['attendent_is_superattendent'].value_counts()

attendent_is_superattendent
False    19515
True      3011
NA          26
Name: count, dtype: int64

attendent_response_rate

In [56]:
data['attendent_response_rate'] = data['attendent_response_rate'].replace({'':np.nan,'N/A':np.nan})
data['attendent_response_rate'] = data['attendent_response_rate'].astype(float)

In [57]:
data['attendent_response_rate'].dtype

dtype('float64')

In [58]:
data['attendent_response_rate'].unique()

array([1.  ,  nan, 0.89, 0.9 , 0.97, 0.78, 0.8 , 0.67, 0.5 , 0.19, 0.98,
       0.71, 0.7 , 0.74, 0.83, 0.  , 0.88, 0.33, 0.92, 0.94, 0.4 , 0.6 ,
       0.82, 0.75, 0.96, 0.52, 0.63, 0.95, 0.43, 0.57, 0.86, 0.38, 0.54,
       0.17, 0.91, 0.93, 0.73, 0.58, 0.84, 0.87, 0.3 , 0.79, 0.25, 0.81,
       0.2 , 0.56, 0.46, 0.72, 0.77, 0.64, 0.69, 0.29, 0.68, 0.76, 0.65,
       0.22, 0.18, 0.13, 0.62, 0.85, 0.44, 0.14, 0.48, 0.1 , 0.55])

attendent_response_time

In [59]:
data['attendent_response_time']=data['attendent_response_time'].replace({'':'NA','N/A':'NA'})  # Replace empty strings with NaN


In [60]:
data['attendent_response_time'].isnull().sum()

12894

In [61]:
data['attendent_response_time'].value_counts()

attendent_response_time
within an hour        5081
within a few hours    2127
within a day          2060
a few days or more     390
Name: count, dtype: int64

In [62]:
data['attendent_response_time'].dtype

dtype('O')

attendent_location

In [66]:
a=data['attendent_location'].unique()
pd.set_option('display.max_rows', None)
a_list = a.tolist()
print(a_list)


['Berlin, Berlin, Germany', 'DE', 'London, England, United Kingdom', nan, 'Dubai, Dubai, United Arab Emirates', 'Saint Johann, Baden-Württemberg, Germany', 'Russia', 'Obermaßfeld-Grimmenthal, Thuringia, Germany', 'Achim, Lower Saxony, Germany', 'Cairo, Cairo Governorate, Egypt', 'Bielefeld, North Rhine-Westphalia, Germany', 'Istanbul, Istanbul, Turkey', 'Addis Ababa, Addis Ababa, Ethiopia', 'County Clare, Ireland', 'Becherbach, Rhineland-Palatinate, Germany', 'Deutschland', 'Fontenay-sous-Bois, Île-de-France, France', 'Bad Wildungen, Hesse, Germany', 'Germany', 'The Hague, South Holland, Netherlands', 'India', 'Sarstedt, Niedersachsen, Germany', 'Bovenden, Lower Saxony, Germany', 'Bergen, Hordaland, Norway', 'England, United Kingdom', 'Berlin (born and raised, Baby)', 'Paderborn, North Rhine-Westphalia, Germany', 'Cologne, North Rhine-Westphalia, Germany', 'Nordfriesland, Schleswig-Holstein, Germany', 'Palma, Balearic Islands, Spain', 'Munich, Bayern, Germany', 'Chemnitz, Saxony, Germa

In [69]:
data['attendent_country'].unique()

array(['Germany', 'DE', 'United Kingdom', 'NA', 'United Arab Emirates',
       'Russia', 'Egypt', 'Turkey', 'Ethiopia', 'Ireland', 'Deutschland',
       'France', 'Netherlands', 'India', 'Norway', 'Baby)', 'Spain',
       'Switzerland', 'United States', 'Greece', 'Denmark', 'Italy',
       'Israel', 'LU', 'Poland', 'Sweden', 'South Africa', 'Australia',
       'IT', 'US', 'Brazil', 'Tel Aviv', 'CH', 'UK', 'Croatia',
       'The Netherlands', 'Portugal', 'Belgium', 'BW', 'Berlin/Tel Aviv',
       'Argentina', 'Namibia', 'Taiwan', 'GB', 'Europe', 'Canada', 'CN',
       'FR', 'Ludwigsfelde ... 20km südlich von Berlin/Lichterfelde',
       'On this Planet', 'Hongkong', 'Berlin Wannsee', 'China', 'Romania',
       'NY', 'Singapore', 'Berlin/ Hamburg', 'Uruguay', 'GR', 'Finland',
       'MX', 'Slovenia', 'Malta', 'Lebanon', 'nicosia', 'Bulgaria',
       'Morocco', 'Austria', 'London', 'Berlin-Pankow', 'Estonia', 'Peru',
       'Hamburg', 'South Korea', 'Colombia', 'CZ', 'Mexico', 'Hong Kong'

attendent_since

In [63]:
data['attendent_since'].fillna(np.nan,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_17348\1936228796.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['attendent_since'].fillna(np.nan,inplace=True)


In [64]:
data['attendent_since'].isnull().sum()

26

In [65]:
data['attendent_since'].dtypes

dtype('float64')

reviews_per_month

In [135]:
data['reviews_per_month'].isnull().sum()

3914

In [136]:
data['reviews_per_month'].unique()

array([      nan, 2.000e+00, 4.000e+00, 1.000e+00, 3.000e+00, 5.000e+00,
       3.240e+00, 6.000e+00, 1.870e+00, 3.670e+00, 3.160e+00, 6.980e+00,
       1.400e+00, 1.110e+00, 3.190e+00, 4.410e+00, 4.360e+00, 2.430e+00,
       6.180e+00, 5.770e+00, 1.760e+00, 5.510e+00, 2.450e+00, 1.550e+00,
       4.620e+00, 1.850e+00, 6.770e+00, 4.150e+00, 3.530e+00, 1.820e+00,
       1.500e+00, 2.610e+00, 3.810e+00, 8.000e-01, 3.040e+00, 2.730e+00,
       4.810e+00, 2.590e+00, 2.650e+00, 4.340e+00, 4.640e+00, 1.450e+00,
       8.100e-01, 9.100e-01, 2.820e+00, 7.260e+00, 2.690e+00, 2.020e+00,
       1.910e+00, 7.200e-01, 2.080e+00, 2.100e+00, 3.210e+00, 1.700e+00,
       9.700e-01, 1.610e+00, 3.460e+00, 2.800e+00, 4.500e+00, 1.650e+00,
       2.030e+00, 2.530e+00, 2.470e+00, 3.820e+00, 3.600e+00, 7.100e-01,
       1.480e+00, 1.780e+00, 1.090e+00, 4.900e+00, 1.030e+00, 1.360e+00,
       1.150e+00, 3.570e+00, 5.000e-01, 1.640e+00, 6.410e+00, 3.610e+00,
       6.990e+00, 2.750e+00, 5.900e-01, 3.130e+00, 

In [137]:
data.loc[data['reviews_per_month'] > 30, 'reviews_per_month'] = 30


In [138]:
data['reviews_per_month'].dtypes

dtype('float64')

require_guest_phone_verification

In [131]:
data['require_guest_phone_verification'].isnull().sum()

0

In [132]:
data['require_guest_phone_verification'].replace({'f':False,'t':True},inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\2543777168.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['require_guest_phone_verification'].replace({'f':False,'t':True},inplace=True)
C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\2543777168.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', T

In [133]:
data['require_guest_phone_verification'].value_counts()

require_guest_phone_verification
False    22273
True       279
Name: count, dtype: int64

In [134]:
data['require_guest_phone_verification'].dtypes

dtype('bool')

require_guest_profile_picture

In [127]:
data['require_guest_profile_picture'].isnull().sum()

0

In [128]:
data['require_guest_profile_picture'].replace({'f':False,'t':True},inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\4194462320.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['require_guest_profile_picture'].replace({'f':False,'t':True},inplace=True)
C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\4194462320.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True

In [129]:
data['require_guest_profile_picture'].value_counts()

require_guest_profile_picture
False    22396
True       156
Name: count, dtype: int64

In [130]:
data['require_guest_profile_picture'].dtypes

dtype('bool')

cancellation_policy

In [123]:
data['cancellation_policy'].isnull().sum()

0

In [124]:
data['cancellation_policy'] = data['cancellation_policy'].str.lower().str.replace('_', ' ').str.strip()


In [125]:
data['cancellation_policy'].unique()

array(['flexible', 'strict 14 with grace period', 'moderate',
       'super strict 30', 'super strict 60'], dtype=object)

In [126]:
data['cancellation_policy'].dtypes

dtype('O')

is_business_travel_ready

In [115]:
data['is_business_travel_ready'].isnull().sum()

0

In [116]:
data['is_business_travel_ready'].replace({'f':False,'t':True},inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\751113150.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['is_business_travel_ready'].replace({'f':False,'t':True},inplace=True)
C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\751113150.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  da

In [117]:
data['is_business_travel_ready'].value_counts()

is_business_travel_ready
False    22552
Name: count, dtype: int64

In [118]:
data['is_business_travel_ready'].dtypes

dtype('bool')

instant_bookable

In [119]:
data['instant_bookable'].isnull().sum()

0

In [120]:
data['instant_bookable'].replace({'f':False,'t':True},inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\708450746.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['instant_bookable'].replace({'f':False,'t':True},inplace=True)
C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\708450746.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['inst

In [121]:
data['instant_bookable'].value_counts()

instant_bookable
False    15518
True      7034
Name: count, dtype: int64

In [122]:
data['instant_bookable'].dtypes

dtype('bool')

license

In [102]:
data['license'].isnull().sum()

20914

In [103]:
data['license'].fillna('na',inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\1542853083.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['license'].fillna('na',inplace=True)


In [104]:
data['license'].unique()

array(['08/Z/RA/006663-18', '02/Z/ZA/004738-17 Mindestaufenthalt 60',
       '02/Z/AZ/008691-18', ...,
       'Genehmigung BA Pankow 03/Z/ZA/002715-17 Genehigungsbescheid vom 16.05.2017',
       '03/Z/RA/003410-18', 'na'], dtype=object)

In [105]:
import pandas as pd
import re

def count_numbers(license_str):
    # Convert the value to a string
    license_str = str(license_str)
    return len(re.findall(r'\d', license_str))

# Create license_provided column based on the number of numeric characters
data['license_provided'] = data['license'].apply(lambda x: True if count_numbers(x) >= 4 else False)


In [106]:
data['license'].dtypes

dtype('O')

In [107]:
data['license_provided'].value_counts()

license_provided
False    21034
True      1518
Name: count, dtype: int64

In [111]:
data.loc[(data['license_provided'] == False) & (data['requires_license'] == True), 'license'] = 'not provided'

In [112]:
count = data[data['license'] == 'not provided'].shape[0]
print(f"Number of rows where license is 'not provided': {count}")

Number of rows where license is 'not provided': 21026


In [113]:
data.shape[0]-8-count

1518

In [114]:
data['requires_license'].dtypes

dtype('bool')

requires_license

In [98]:
data['requires_license'].isnull().sum()

0

In [99]:
data['requires_license'].replace({'f':False,'t':True},inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\474480720.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['requires_license'].replace({'f':False,'t':True},inplace=True)
C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\474480720.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['requ

In [100]:
data['requires_license'].value_counts()

requires_license
True     22544
False        8
Name: count, dtype: int64

In [101]:
data['requires_license'].dtypes

dtype('bool')

review_scores_value

In [95]:
data['review_scores_value'].isnull().sum()

4435

In [96]:
data['review_scores_value'].unique()

array([nan, 10.,  9.,  8.,  6.,  7.,  2.,  4.,  5.,  3.])

In [97]:
import numpy as np
data['review_scores_value'].fillna(0,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\2571066741.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['review_scores_value'].fillna(0,inplace=True)


review_scores_location

In [91]:
data['review_scores_location'].isnull().sum()

4431

In [92]:
data['review_scores_location'].unique()

array([nan, 10.,  9.,  8.,  7.,  2.,  6.,  4.,  5.])

In [93]:
data['review_scores_location'].fillna(0,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\2388830286.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['review_scores_location'].fillna(0,inplace=True)


In [94]:
data['review_scores_location'].dtypes

dtype('float64')

review_scores_communication

In [87]:
data['review_scores_communication'].dtypes

dtype('float64')

In [88]:
data['review_scores_communication'].isnull().sum()

4418

In [89]:
data['review_scores_communication'].fillna(0,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\3333512195.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['review_scores_communication'].fillna(0,inplace=True)


In [90]:
data['review_scores_communication'].unique()

array([ 0., 10.,  8.,  9.,  2.,  7.,  5.,  6.,  4.,  3.])

review_scores_checkin

In [83]:
data['review_scores_checkin'].isnull().sum()

4432

In [84]:
data['review_scores_checkin'].dtypes

dtype('float64')

In [85]:
data['review_scores_checkin'].fillna(0,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\780018989.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['review_scores_checkin'].fillna(0,inplace=True)


In [86]:
data['review_scores_checkin'].unique()

array([ 0., 10.,  7.,  8.,  9.,  2.,  6.,  4.,  5.])

review_scores_cleanliness

In [82]:
print(data['review_scores_cleanliness'].dtypes)
print(data['review_scores_cleanliness'].unique())
print(data['review_scores_cleanliness'].isnull().sum())
data['review_scores_cleanliness'].fillna(0,inplace=True)

float64
[nan 10.  9.  8.  2.  7.  6.  5.  4.  3.]
4411


C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\2403760143.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['review_scores_cleanliness'].fillna(0,inplace=True)


review_scores_accuracy

In [81]:
print(data['review_scores_accuracy'].dtypes)
print(data['review_scores_accuracy'].unique())
print(data['review_scores_accuracy'].isnull().sum())
data['review_scores_accuracy'].fillna(0,inplace=True)

float64
[nan 10.  8.  7.  9.  2.  6.  4.  5.  3.]
4414


C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\2785326484.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['review_scores_accuracy'].fillna(0,inplace=True)


review_scores_rating

In [80]:
print(data['review_scores_rating'].dtypes)
print(data['review_scores_rating'].unique())
print(data['review_scores_rating'].isnull().sum())
data['review_scores_rating'].fillna(0,inplace=True)

float64
[ nan 100.  93.  92.  80.  88.  90.  95.  98.  99.  97.  94.  91.  96.
  85.  87.  89.  78.  20.  83.  73.  81.  77.  84.  86.  75.  82.  60.
  67.  76.  53.  79.  70.  40.  72.  74.  69.  71.  64.  50.  30.  65.
  68.  56.  33.  63.  57.]
4389


C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\498766367.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['review_scores_rating'].fillna(0,inplace=True)


last_review

In [79]:
print(data['last_review'].dtypes)
print(data['last_review'].unique())
print(data['last_review'].isnull().sum())
data['last_review'].fillna(np.nan,inplace=True)

float64
[   nan 43409. 43407. ... 42837. 42875. 41724.]
3908


C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\708650849.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['last_review'].fillna(np.nan,inplace=True)


first_review

In [78]:
print(data['first_review'].dtypes)
print(data['first_review'].unique())
print(data['first_review'].isnull().sum())
data['first_review'].fillna(np.nan,inplace=True)

float64
[   nan 43406. 43399. ... 41602. 42021. 41665.]
3914


C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\4080858715.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['first_review'].fillna(np.nan,inplace=True)


number_of_reviews

In [77]:
print(data['number_of_reviews'].isnull().sum())
print(data['number_of_reviews'].dtypes)

0
int64


availability_365

In [76]:
print(data['availability_365'].isnull().sum())
print(data['availability_365'].dtypes)

0
int64


availability_90

In [75]:
print(data['availability_90'].isnull().sum())
print(data['availability_90'].dtypes)

0
int64


availability_60

In [74]:
print(data['availability_60'].isnull().sum())
print(data['availability_60'].dtypes)

0
int64


availability_30

In [73]:
print(data['availability_30'].isnull().sum())
print(data['availability_30'].dtypes)

0
int64


has_availability

In [71]:
data['has_availability'].replace({'t':True},inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\78632130.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['has_availability'].replace({'t':True},inplace=True)
C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\78632130.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['has_availability

In [72]:
data['has_availability'].value_counts()

has_availability
True    22552
Name: count, dtype: int64

calendar_updated

In [67]:
data['calendar_updated'].isnull().sum()

0

In [68]:
data['calendar_updated']=data['calendar_updated'].str.strip().str.lower()

In [69]:
data['calendar_updated'].unique()

array(['today', '5 days ago', '4 days ago', '2 weeks ago', 'a week ago',
       'yesterday', '4 weeks ago', '3 weeks ago', '2 days ago',
       '6 weeks ago', '3 days ago', '2 months ago', '6 days ago',
       '7 weeks ago', '3 months ago', '5 weeks ago', '4 months ago',
       '5 months ago', '6 months ago', '9 months ago', '1 week ago',
       '7 months ago', '8 months ago', '47 months ago', '31 months ago',
       '23 months ago', '19 months ago', '25 months ago', '28 months ago',
       '34 months ago', '33 months ago', '11 months ago', '15 months ago',
       '16 months ago', '14 months ago', '12 months ago', '18 months ago',
       '17 months ago', '13 months ago', '42 months ago', 'never',
       '40 months ago', '37 months ago', '10 months ago', '35 months ago',
       '27 months ago', '21 months ago', '24 months ago', '43 months ago',
       '29 months ago', '41 months ago', '36 months ago', '39 months ago',
       '30 months ago', '20 months ago', '26 months ago', '32 months 

In [70]:
data['calendar_updated'].dtypes

dtype('O')

minimum_nights

In [60]:
data['minimum_nights'].isnull().sum()

0

In [59]:
data['minimum_nights'] = data['minimum_nights'].clip(upper=10)

In [61]:
data['minimum_nights'].unique()

array([ 1, 10,  2,  3,  6,  5,  4,  7,  9,  8], dtype=int64)

In [62]:
data['minimum_nights'].dtypes

dtype('int64')

maximum_nights

In [63]:
data['maximum_nights'].isnull().sum()

0

In [64]:
data['maximum_nights'] = data['maximum_nights'].clip(upper=180)

In [65]:
data['maximum_nights'].unique()

array([180,  15,   8, 150,   3,   5,  90,  30,   7,  31,  32,  93,  44,
        13,  14,  60,  28,  10,  12,  29,   1,   9,  17,  22,  33,  50,
        21,  25,  65,  20,  89, 111,  27,   6, 120,  40,  61,  16,  75,
        80,  35, 100,  95,  62,  92,   4, 112,   2,  58,  23,  55,  18,
        42,  38,  19,  45, 140,  88, 160,  70,  66,  64,  24, 122,  49,
       125,  96, 115,  11,  37,  26,  99,  78, 102,  63,  79, 121,  85,
        34, 119,  54,  36, 170, 141,  41,  39, 105, 176, 101,  57,  52,
        73, 110, 169,  56,  43,  48,  87, 117,  51, 132, 152, 159,  77,
       116, 131, 104,  67,  46,  81,  47, 114,  59, 124, 156, 135, 130,
        86, 151, 123,  72,  97], dtype=int64)

In [66]:
data['maximum_nights'].dtypes

dtype('int64')

extra_people

In [57]:
data['extra_people'].isnull().sum()

0

In [58]:
data['extra_people'].dtypes

dtype('int64')

guests_included

In [55]:
data['guests_included'].isnull().sum()

0

In [56]:
data['guests_included'].dtypes

dtype('int64')

cleaning_fee

In [52]:
data['cleaning_fee'].dtypes

dtype('float64')

In [53]:
data['cleaning_fee'].isnull().sum()

7146

In [54]:
data['cleaning_fee'].fillna(np.nan,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\3429892558.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['cleaning_fee'].fillna(np.nan,inplace=True)


security_deposit

In [49]:
data['security_deposit'].dtypes

dtype('float64')

In [50]:
data['security_deposit'].isnull().sum()

9361

In [51]:
data['security_deposit'].fillna(np.nan,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\1150049356.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['security_deposit'].fillna(np.nan,inplace=True)


monthly_price

In [46]:
data['monthly_price'].dtypes

dtype('float64')

In [47]:
data['monthly_price'].isnull().sum()

19893

In [48]:
data['monthly_price'].fillna(np.nan,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\2665225775.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['monthly_price'].fillna(np.nan,inplace=True)


weekly_price

In [44]:
data['weekly_price'].dtypes

dtype('float64')

In [45]:
data['weekly_price'].isnull().sum()

18871

In [96]:
data['weekly_price'].fillna(np.nan,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_17164\1163550806.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['weekly_price'].fillna(np.nan,inplace=True)


Price

In [42]:
data['price'].dtypes

dtype('int64')

In [43]:
data['price'].isnull().sum()

0

amenities

In [40]:
data['amenities'] = data['amenities'].str.replace(r'[^\w\s,]', '', regex=True).str.lower().str.strip()


In [41]:
data['amenities']

0        tv,wifi,kitchen,free street parking,hot tub,he...
1        tv,wifi,kitchen,free street parking,heating,wa...
2        wifi,kitchen,heating,washer,first aid kit,esse...
3        wifi,kitchen,heating,washer,dryer,essentials,i...
4        wifi,air conditioning,kitchen,free parking on ...
5        tv,wifi,kitchen,paid parking off premises,elev...
6        tv,wifi,air conditioning,kitchen,smoking allow...
7        tv,cable tv,internet,wifi,wheelchair accessibl...
8        tv,internet,wifi,kitchen,elevator,buzzerwirele...
9        tv,wifi,kitchen,free parking on premises,indoo...
10       wifi,kitchen,heating,washer,smoke detector,ess...
11       tv,wifi,kitchen,paid parking off premises,heat...
12       wifi,kitchen,free street parking,heating,washe...
13       wifi,kitchen,heating,smoke detector,essentials...
14       tv,wifi,kitchen,pets allowed,free street parki...
15       tv,internet,wifi,kitchen,pets allowed,elevator...
16       wifi,kitchen,smoking allowed,pets allowed,free.

bed_type

In [35]:
data['bed_type'].isnull().sum()

0

In [38]:
data['bed_type'].unique()

array(['real bed', 'futon', 'pull-out sofa', 'couch', 'airbed'],
      dtype=object)

In [37]:
data['bed_type']=data['bed_type'].str.strip().str.lower()

beds

In [31]:
data['beds'].isnull().sum()

40

In [32]:
data['beds'].dtypes

dtype('float64')

In [33]:
data['beds'].unique()

array([ 2.,  1.,  4.,  3.,  5.,  7.,  6.,  0., nan,  8., 15.,  9., 10.,
       13., 11., 12., 22., 16., 14.])

In [34]:
import numpy as np
data['beds'].fillna(np.nan,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\3614363184.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['beds'].fillna(np.nan,inplace=True)


bedrooms

In [27]:
data['bedrooms'].dtypes

dtype('float64')

In [28]:
data['bedrooms'].isnull().sum()

18

In [29]:
data['bedrooms'].fillna(np.nan,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\366905896.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['bedrooms'].fillna(np.nan,inplace=True)


In [30]:
data['bedrooms'].unique()

array([ 2.,  1.,  0.,  3.,  4.,  5., 12.,  7., nan,  6.,  8.,  9., 10.])

bathrooms

In [23]:
data['bathrooms'].unique()

array([3. , 1. , 2. , 1.5, 2.5, 0.5, 3.5, 7. , 5. , 4. , 4.5, nan, 0. ,
       6. , 8. , 7.5, 8.5])

In [24]:
data['bathrooms'].isnull().sum()

32

In [26]:
import numpy as np
data['bathrooms'].fillna(np.nan,inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_8068\3534655098.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['bathrooms'].fillna(np.nan,inplace=True)


accommodates

In [21]:
data['accommodates'].isnull().sum()

0

In [22]:
data['accommodates'].unique()

array([ 4,  2,  3,  5,  6,  1,  7,  8, 11, 14, 10,  9, 12, 16, 15, 13],
      dtype=int64)

room_type

In [19]:
data['room_type'].unique()

array(['entire apt', 'private room', 'shared room'], dtype=object)

In [18]:
data['room_type'] = data['room_type'].str.replace('home/', '', regex=False).str.lower().str.strip()

In [20]:
data['room_type'].isnull().sum()

0

property_type

In [13]:
data['property_type'].isnull().sum()

0

In [16]:
data['property_type'].unique()

array(['apartment', 'condominium', 'serviced apartment', 'loft',
       'townhouse', 'aparthotel', 'pension (south korea)', 'camper/rv',
       'house', 'boat', 'hotel', 'hostel', 'bed and breakfast',
       'guest suite', 'boutique hotel', 'bungalow', 'guesthouse', 'villa',
       'tiny house', 'chalet', 'houseboat', 'other', 'cabin', 'cottage',
       'casa particular (cuba)', 'island', 'train', 'resort', 'cave',
       'in-law', 'castle', 'barn', 'tipi'], dtype=object)

In [15]:
data['property_type'] = data['property_type'].str.lower().str.strip()

is_location_exact

In [12]:
data['is_location_exact'].isnull().sum()

0

In [47]:
data['is_location_exact'].replace({'t':True,'f':False},inplace=True)

C:\Users\MRITH\AppData\Local\Temp\ipykernel_11536\1452383665.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['is_location_exact'].replace({'t':True,'f':False},inplace=True)


longitude

In [9]:
print(data['longitude'].isnull().sum())
print(data['longitude'].dtypes)

0
float64


latitude

In [10]:
print(data['latitude'].isnull().sum())
print(data['latitude'].dtypes)

0
float64


country

In [11]:
data['country'].str.lower().str.strip()

0        germany
1        germany
2        germany
3        germany
4        germany
5        germany
6        germany
7        germany
8        germany
9        germany
10       germany
11       germany
12       germany
13       germany
14       germany
15       germany
16       germany
17       germany
18       germany
19       germany
20       germany
21       germany
22       germany
23       germany
24       germany
25       germany
26       germany
27       germany
28       germany
29       germany
30       germany
31       germany
32       germany
33       germany
34       germany
35       germany
36       germany
37       germany
38       germany
39       germany
40       germany
41       germany
42       germany
43       germany
44       germany
45       germany
46       germany
47       germany
48       germany
49       germany
50       germany
51       germany
52       germany
53       germany
54       germany
55       germany
56       germany
57       germany
58       germa

Name

In [ ]:
data['name'].isnull().sum()

In [ ]:
data['name'].fillna('na',inplace=True)

In [ ]:
data['name'].isnull().sum()

In [ ]:
data['name'][20509]

In [ ]:
import pandas as pd
import re
from googletrans import Translator



translator = Translator()

def translate_text(text):
    if pd.isna(text):  # Check for NaN values
        return 'na'  # Replace NaN with a specific value
    try:
        translation = translator.translate(text, dest='en')
        print(translation.text)
        return translation.text if translation else ''  # Handle None return value
    except Exception as e:
        print(f"Error translating text: {text}. Error: {e}")
        return ''  # Return an empty string in case of error

def clean_text(text):
    if pd.isna(text):  # Check for NaN values
        return ''  # Replace NaN with an empty string
    text = text.lower()  # Lowercase
    text = re.sub(r'[^a-z0-9\s]', '', text)  # Remove special characters
    text = ' '.join(text.split())  # Trim whitespaces
    return text.strip()

# First, translate to English
data['translated_name'] = data['name'].apply(translate_text)

# Then, clean the translated text
data['cleaned_name'] = data['translated_name'].apply(clean_text)

# Print the cleaned names
print(data[['name', 'translated_name', 'cleaned_name']])

attendent_name

In [ ]:
data['attendent_name'].isnull().sum()

In [ ]:
data['attendent_name'].dtypes

In [ ]:
data['attendent_name']=data['attendent_name'].fillna('na')

In [ ]:
data['attendent_name'].isnull().sum()

In [ ]:
import pandas as pd
import re
from googletrans import Translator



translator = Translator()

def translate_text(text):
    if pd.isna(text):  # Check for NaN values
        return 'na'  # Replace NaN with a specific value
    try:
        translation = translator.translate(text, dest='en')
        print(translation.text)
        return translation.text if translation else ''  # Handle None return value
    except Exception as e:
        print(f"Error translating text: {text}. Error: {e}")
        return ''  # Return an empty string in case of error

def clean_text(text):
    if pd.isna(text):  # Check for NaN values
        return ''  # Replace NaN with an empty string
    text = text.lower()  # Lowercase
    text = re.sub(r'[^a-z0-9\s]', '', text)  # Remove special characters
    text = ' '.join(text.split())  # Trim whitespaces
    return text.strip()

# First, translate to English
data['translated2_name'] = data['attendent_name'].apply(translate_text)

# Then, clean the translated text
data['cleaned2_name'] = data['translated2_name'].apply(clean_text)




In [ ]:
filename = 'property_transformed_summary.xlsx'

# Save DataFrame to Excel
data.to_excel(filename, index=False)